#include "Lexer.h"
#include "postfixParser.h"
#include "rpnArrayEval.h"
#include <stdio.h>
#include <stdlib.h>

int main(void){
    //print the tokens generated by the user
    char input[]="(tan(5.76 * x)-ln(9.17 * x))";
    token *tokensHead=lex(input);

    token *cToken = tokensHead;
    printf("String: %s\n",input);
    while(cToken!=NULL){
        printf("Token: %s, Type: %d\n",cToken->text, cToken->type);
        cToken=cToken->nextToken;
    }

    //Call parser and print the postfix Array
    Stack *postfixArray=parser(tokensHead);
    printf("\nPostfix:\n");
    for(int i=1;i<=postfixArray->top;i++)
        printf("%s\n",postfixArray->stack[i].text);

    //Call eval and print the value at x=10
    double x,val;
    printf("Enter the decimal number, the expression is to be evaluated at>");
    scanf("%lf",&x);
    val=eval(postfixArray,x);
    printf("\nThe value of the entered expression at %lf is %lf",x,val);
    freeTokens(tokensHead);
    return(0);
}
